import 'dart:async';
import 'dart:io';
import 'package:equatable/equatable.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:path/path.dart';
import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import 'dart:convert';
import 'package:http/http.dart' as http;
import 'dart:math';
import 'dart:math' show cos, sqrt, asin;
part 'config.dart';
part 'index.dart';
part 'route.dart';
part 'styling.dart';
part 'shr/routeFunction.dart';
part 'shr/global.dart';
part 'shr/api.dart';
part 'screens/splash.screen.dart';
part 'screens/splash.controller.dart';
part 'extensions/hex.extension.dart';
part 'models/auth.model.dart';
part 'models/user.model.dart';
part 'services/auth.service.dart';
part 'screens/welcome.screen.dart';
